"""
Cisco UCS Central Password Reset ISO 1.5.1c — RE Module
Source: ucs-central-passreset.1.5.1c.iso (/media/cowboy/research/Cisco-UCS/)
Format: Anaconda kickstart-based Red Hat installer ISO
Key files:
  ks.cfg             — default kickstart (no rootpw, basic config only)
  ks_upgrade.cfg     — upgrade-path kickstart (hardcoded root hash)
  images/stage2.img  — Squashfs v3.0 with Anaconda Python runtime
  images/stage2.img/usr/lib/anaconda/ucscentral.py  — UCS Central config module
  images/stage2.img/usr/lib/anaconda/iw/ucscentralreset_gui.py — Password reset GUI
"""

FIRMWARE = {
    "target":   "Cisco UCS Central Password Reset ISO",
    "version":  "1.5.1c",
    "source":   "ucs-central-passreset.1.5.1c.iso",
    "iso_date": "2017-02-26",
    "base":     "Red Hat / Anaconda kickstart installer (CentOS 6 era)",
    "findings": ["UCSC-F1", "UCSC-F2", "UCSC-F3"],
}

# ─────────────────────────────────────────────────────────
# UCSC-F1: Hardcoded AES-128 key "theKeyForEncryptingTheSharedSecret"
#          used to encrypt UCS Central shared secret and restore passwords
# ─────────────────────────────────────────────────────────
UCSC_F1 = {
    "id":       "UCSC-F1",
    "title":    "ucscentral.py encrypt() uses hardcoded AES-128 key 'theKeyForEncryptingTheSharedSecret' "
                "to encrypt UCS Central shared secret and restore passwords in kickstart config files",
    "status":   "CONFIRMED — images/stage2.img/usr/lib/anaconda/ucscentral.py:53-63",
    "severity": "CRITICAL",

    "vulnerable_code": (
        "# ucscentral.py:53-63\n"
        "def encrypt(self, plaintext):\n"
        "    key = \"theKeyForEncryptingTheSharedSecret\"\n"
        "    cmd = \"echo '%s' | /usr/lib/anaconda/openssl enc -e -k '%s' -aes128 -a\" % (plaintext, key)\n"
        "    pipe = subprocess.Popen([cmd], stdout=subprocess.PIPE, shell=True)\n"
        "    data = pipe.stdout.read()\n"
        "    return data.rstrip('\\n')"
    ),

    "encrypted_values": {
        "sharedSecret": (
            "UCS Central shared secret — authenticates UCS Central to all registered UCS Manager domains. "
            "Written to kickstart setup file as: 'secret <ciphertext>'"
        ),
        "restorePass": (
            "Backup/restore source password — written to kickstart restore file as: 'restorePass <ciphertext>'"
        ),
    },

    "decryption_command": (
        "echo '<ciphertext_from_ks_file>' | "
        "openssl enc -d -k 'theKeyForEncryptingTheSharedSecret' -aes128 -a"
    ),

    "attack_path": (
        "1. Obtain any UCS Central kickstart config file generated by the installer\n"
        "   (written to the installed OS during setup — path /opt/cisco/core/... or /etc/sysconfig/firstboot)\n"
        "2. Find the 'secret <ciphertext>' line in the config\n"
        "3. Decrypt: echo '<ciphertext>' | openssl enc -d -k 'theKeyForEncryptingTheSharedSecret' -aes128 -a\n"
        "4. Use the recovered sharedSecret to authenticate as UCS Central to any connected UCS Manager\n"
        "UCS Manager shared secret enables: full fabric management API access, policy deployment, "
        "service profile management, firmware staging across all connected UCS domains."
    ),

    "scope": (
        "Affects every UCS Central 1.5.1c installation that used the installer/passreset ISO to set up. "
        "The sharedSecret is the trust anchor between UCS Central and all registered UCS Managers — "
        "compromise of this secret breaks the entire trust model. "
        "The key is compiled into the installer Python module and is not configurable."
    ),

    "shell_injection_note": (
        "The encrypt() function uses shell=True with user-supplied plaintext interpolated into the command:\n"
        "cmd = \"echo '%s' | ...\" % (plaintext, key)\n"
        "If the sharedSecret contains a single quote, the shell command breaks. "
        "With input like \"'; malicious_cmd; '\", shell injection occurs in the installer context (running as root). "
        "The sharedSecret is entered by the UCS Central administrator, so this is self-exploitation, but "
        "the attack surface exists in the subprocess invocation."
    ),
}

# ─────────────────────────────────────────────────────────
# UCSC-F2: Hardcoded MD5-crypt root hash in ks_upgrade.cfg
#          — upgrade-path kickstart sets root password to Cisco-controlled value
# ─────────────────────────────────────────────────────────
UCSC_F2 = {
    "id":       "UCSC-F2",
    "title":    "ks_upgrade.cfg contains hardcoded MD5-crypt root password hash — "
                "upgrade-path kickstart sets root to a Cisco-controlled static password on every system",
    "status":   "CONFIRMED — ks_upgrade.cfg in ucs-central-passreset.1.5.1c.iso root",
    "severity": "HIGH",

    "kickstart_rootpw_line": "rootpw --iscrypted $1$ToWcsC4R$XaYfvve4hPK/EhCIEuXlE/",

    "hash_details": {
        "format":    "MD5-crypt ($1$ prefix, hashcat mode 500, john format md5crypt)",
        "salt":      "ToWcsC4R",
        "hash":      "XaYfvve4hPK/EhCIEuXlE/",
        "crackable": "MD5-crypt is computationally weak — offline cracking feasible with GPU",
    },

    "impact": (
        "The upgrade-path kickstart (ks_upgrade.cfg) sets the root password of the target UCS Central "
        "system to this static hash on every upgrade. All UCS Central systems upgraded via this ISO path "
        "share the same root password (whatever this hash resolves to). "
        "SSH is opened during the upgrade: 'firewall --enabled --port=22:tcp'. "
        "Anyone who cracks the hash gains root SSH access to every UCS Central system that used this ISO. "
        "ks_upgrade.cfg is not used in the default boot path (which uses ks.cfg with no rootpw). "
        "It is invoked when the upgrade mode is explicitly selected or passed as a kernel parameter."
    ),

    "crack_attempts": (
        "Hash was not cracked with rockyou.txt, common Cisco passwords, mask attacks (Cisco?d?d?d?d, ?u?l?l?l?l?l?d?d). "
        "Password is likely non-trivial. Recommend extended GPU-based cracking with hashcat mode 500."
    ),
}

# ─────────────────────────────────────────────────────────
# UCSC-F3: Dead code — "disable root" was never implemented; root stays active
# ─────────────────────────────────────────────────────────
UCSC_F3 = {
    "id":       "UCSC-F3",
    "title":    "ucscentral.py write() has commented-out 'disable root' code that was never implemented — "
                "root account remains active with /bin/bash shell contrary to design intent",
    "status":   "CONFIRMED — images/stage2.img/usr/lib/anaconda/ucscentral.py:130-141",
    "severity": "LOW",

    "dead_code": (
        "#disable root\n"
        "#log.info('Disabling root user')\n"
        "#os.rename(instPath + '/etc/passwd', instPath + '/etc/passwd.orig')\n"
        "#passwd = open(instPath + '/etc/passwd.orig', 'r')\n"
        "#passwd2 = open(instPath + '/etc/password', 'w')\n"
        "#for line in passwd:\n"
        "#    if re.search('^root', line) != None:\n"
        "#        passwd2.write('root:x:0:0:root:/root:/sbin/nologin')\n"
        "#    else:\n"
        "#        passwd2.write(line)"
    ),

    "impact": (
        "The installer was designed to set root shell to /sbin/nologin but this code was commented out. "
        "Root retains the default /bin/bash (or /bin/sh) shell on installed systems. "
        "Any code path that provides a root shell (UCSC-F2, local console access, SUID abuse) "
        "yields a fully interactive root session rather than a nologin rejection."
    ),
}

PASSWORD_VALIDATION_RULES = {
    "min_length": 8,
    "max_length": 64,
    "require_3_of_4": ["A-Z", "a-z", "0-9", "special (no ? = $ space)"],
    "max_char_repeat": 2,
    "note": "validatePassword() in ucscentral.py:145-158",
}

FINDINGS = [UCSC_F1, UCSC_F2, UCSC_F3]

if __name__ == "__main__":
    for f in FINDINGS:
        print(f"[{f['severity']:8s}] {f['id']}: {f['title'][:80]}")
