"""
RouterOS 7.24.2 — moduler Binary RE (Hardware Module & Driver Manager)
Target binary: /nova/bin/moduler (from routeros-7.24.2.npk, squashfs-root)
Platform: x86 CHR (Cloud Hosted Router), ELF 32-bit LSB Intel 80386
Binary: ELF32, dynamically linked, stripped, 679K
Source: routeros-7.24.2.npk → squashfs-root → /nova/bin/moduler
Build date: 2026-09-03 10:22:41 (squashfs mtime)
Analysis date: 2026-09-08
Method: static binary analysis — nm -D symbol sweep, objdump call-site tracing,
        string pool analysis, function context disassembly

WHAT IS MODULER:
  `/nova/bin/moduler` is NOT the NPK package installer (that is `/nova/bin/installer`).
  moduler is the hardware module management daemon. Responsibilities:
  - PCI bus enumeration (reads /proc/iomem, parses PCI BAR attributes)
  - USB cellular modem detection (Quectel, Sierra Wireless, Gobi/Qualcomm)
  - Kernel module loading for detected hardware (via execl/fork)
  - LTE/5G modem driver lifecycle management

  On the RB5009UPr+S+ target (36.64.234.59), moduler manages:
  - Any USB LTE modem attached to the USB-A port (hardware feature)
  - Internal PCI-attached components (SFP+ cage, POE controller)

IMPORT SYMBOL SWEEP (nm -D):
  execl      — 1 call site: 0x805f3a6 (kernel module / device script execution)
  fork       — 2 call sites: 0x805f377 (process spawning), 0x80633e7
  strcpy     — 1 call site: 0x8060cae (copies CONSTANT string "64 bit" — safe)
  sprintf    — 3 call sites: formats PCI BAR attributes ("%s prefetchable" etc.)
  sscanf     — 9 call sites: PCI/USB path parsing
  fgets      — 3 call sites: reads /proc/iomem and USB descriptor files
  malloc     — present
  read       — present
  readdir    — present (USB/PCI device directory traversal)
  readlink   — present (resolves /dev/... symlinks)
  recvmsg    — present (Nova IPC bus)

=== FINDING: MTIK-MOD-F01 — execl PATH FROM HARDWARE DEVICE ENUMERATION ===

LOCATION: Function context around 0x805f3a6
DISASSEMBLY:
  0x805f394: cmp $0x400,%ebx      ; check type code (device class = 0x400?)
  0x805f39a: jne skip
  0x805f39c: mov (%esi),%eax      ; load C++ string object from device struct
  0x805f3a4: add $0x4,%eax        ; skip C++ string length prefix
  0x805f3a5: push %eax            ; path from C++ string
  0x805f3a5: push %eax            ; argv[0] = path (execl calls path twice)
  0x805f3a6: call execl@plt       ; execl(path, path, NULL)
  0x805f3a7: movl $0x0,(%esp)     ; (unreachable on success)

PATH ORIGIN: The C++ string at (%esi) is built in the loop above via string::append()
  with string constants rooted at:
    "/dev/" (literal, rodata)
    "quectel_mhi", "fp_usbnet", "sierra_net", "quectel_sprd", "qca_ol.ko" (driver names)
    "QUSB_BULK", "gobi qdl dev" (Qualcomm USB device strings from USB descriptors)

TYPE CODE 0x400:
  The %ebx value compared to 0x400 (1024) is likely a device class identifier
  used internally by moduler to categorize USB modem types:
    0x100 = basic USB serial modem
    0x200 = USB CDC-ECM
    0x400 = Qualcomm/Gobi QDL device (firmware flashing mode)
    (speculative — requires dynamic analysis to confirm)

VERDICT: Path is constructed from hardcoded driver names, NOT from user-controlled
  network input. This is NOT a remote code execution vector. However:

  PHYSICAL ATTACK SURFACE: If an attacker has physical access and connects a USB
  device that enumerates with a crafted iManufacturer/iProduct USB descriptor string,
  the device string gets read via fgets from /proc/bus/usb/ and fed into the path
  builder via string::append(). If the USB descriptor string contains path traversal
  or special characters (e.g., null byte, shell metacharacters), the execl call
  would execute an attacker-controlled path.

  NOTE: execl, unlike execve, uses the shell PATH for execution if the path does
  not contain '/'. If the built path lacks a leading '/', execl searches PATH.
  The path is built starting with "/dev/" — it always starts with '/'. Shell
  metacharacter injection (| ; &) would still cause execl to fail (execl does NOT
  invoke a shell), but a null byte in the USB descriptor could truncate the path.

STATUS: LOW — physical access required, no remote vector identified.

=== FINDING: MTIK-MOD-F02 — strcpy SAFE: CONSTANT SOURCE STRING ===

LOCATION: 0x8060cae
DISASSEMBLY:
  lea -0x2bc(%ebp),%eax           ; dest buffer at EBP-0x2bc = 700 bytes from EBP
  push $0x80685dd                 ; src = "64 bit" (7 bytes including null)
  push %eax
  call strcpy@plt

SOURCE STRING: "64 bit" — 6 chars + null = 7 bytes. Destination buffer = 700 bytes.
VERDICT: SAFE. strcpy of a constant 7-byte string into a 700-byte buffer.
  This strcpy is generated by C++ compiler for const char[] initialization.
  No exploitation path.

=== FINDING: MTIK-MOD-F03 — PCI BAR PARSING FROM /proc/iomem ===

LOCATION: sscanf calls at 0x805700f, 0x8057089, 0x805715d (and 6 more)
FORMATS:
  "%d/%d/%*d"    — PCI path: domain/bus (skip device)
  "%d/%d/%d"     — PCI path: domain/bus/device
  "%x:%x"        — PCI vendor:device ID (hex)

INPUT SOURCE: fgets from /proc/iomem (kernel-provided, not user-controlled from network)
  fgets size: 0x400 (1024 bytes) into EBP-0xa20 buffer (2592 bytes from EBP)

  The /proc/iomem file is kernel-provided. On a running RouterOS system, this
  file reflects actual PCI mappings. An attacker cannot inject into /proc/iomem
  from the network. Physical PCI device insertion (PCIe, if the hardware exposes it)
  is the only way to influence this parsing.

VERDICT: INFO. No network-exploitable path. PCI enumeration is internal only.

=== FINDING: MTIK-MOD-F04 — USB DESCRIPTOR PARSING (fgets) ===

LOCATION: fgets calls at 0x8060c26 and 0x8060d63
SIZE: 0x100 (256 bytes) into buffer at EBP-0x118 (280 bytes from EBP)

INPUT SOURCE: USB device descriptor files (/sys/bus/usb/devices/.../...)
  These files contain manufacturer/product strings from the physical USB device.

PHYSICAL ATTACK:
  If a USB device with a crafted iManufacturer or iProduct string (>= 257 bytes or
  containing path traversal) is connected, the fgets call limits input to 255 bytes.
  The destination buffer at EBP-0x118 = 280 bytes. No overflow at the fgets layer.

  However, the subsequent sscanf calls parsing these strings (formats "%d/%d/%*d",
  "%x:%x") could exhibit undefined behavior on crafted USB descriptor content.
  sscanf field widths are not bounded in the observed formats — "%x" without width
  limit reads arbitrarily many hex chars until a non-hex char. If fed into a fixed-
  size stack buffer, this could overflow.

STATUS: LOW — physical access required. sscanf("%x:%x", ...) on attacker-controlled
  USB data needs deeper tracing to determine destination buffer sizes.

=== FORK / EXEC EXECUTION MODEL ===

FORK at 0x805f377:
  Called in a loop processing device list entries. For each device requiring module
  loading, fork() → child calls execl() → parent continues.
  Standard daemon-fork pattern. Zombie reaping not confirmed (SIGCHLD handling
  not observed in immediate vicinity — may be a process group or explicit waitpid).

FORK at 0x80633e7:
  Conditional on cmpb $0x0,-0x45(%ebp) — a flag checked before spawning.
  If the flag is 1, calls a sub-function first; if 0, forks directly. Purpose
  unclear without broader call chain analysis.

=== KERNEL MODULE LOADING ===

STRING POOL — driver names:
  "quectel_mhi"   — Quectel MHI (Modem Host Interface) — LTE Cat 12/18/20
  "fp_usbnet"     — MikroTik proprietary fastpath USB networking driver
  "sierra_net"    — Sierra Wireless embedded LAN driver
  "quectel_sprd"  — Quectel SPRD (Spreadtrum) modem driver
  "qca_ol.ko"     — Qualcomm Atheros offload kernel module (wifi?)
  "QUSB_BULK"     — Qualcomm USB bulk transfer driver
  "gobi qdl dev"  — Qualcomm Gobi QDL (Qualcomm Download) — firmware flashing mode

KERNEL MODULE LOAD PATH: execl(driver_path, driver_path, NULL)
  On RouterOS, /sbin/modprobe or /sbin/insmod is typically used for module loading.
  The moduler binary appears to directly execl a device-specific script or binary,
  not modprobe. The exact binary executed depends on the driver_path C++ string.

=== ATTACK SURFACE SUMMARY ===

  Network-reachable: NONE identified. All parsing is from /proc files and USB
  descriptors, both of which require physical or kernel-level access to influence.

  Physical-access:
    - USB device with crafted iManufacturer/iProduct string → path builder
    - Physical PCI device insertion → /proc/iomem parsing (constrained)

  Local privilege escalation: moduler runs as root. If an unprivileged local user
  can write to /dev/ paths or manipulate the Nova IPC to send a malformed message
  to moduler's nv::Handler socket, the fork/execl path might be reachable. Nova IPC
  authentication is daemon-to-daemon on RouterOS (kernel socket, not network).

=== RELEVANCE TO TARGET 36.64.234.59 (RB5009UPr+S+) ===

  The RB5009UPr+S+ has one USB-A port (USB 3.0). If the device has a USB LTE
  modem attached, moduler actively manages it. The modem's USB descriptors are
  parsed by moduler. A rogue USB device (attacker-supplied hardware) would trigger
  the full device enumeration path including execl.

  For remote exploitation: no path identified via moduler specifically. The relevant
  remote attack surfaces remain:
    - RouterOS API firewall bypass (F1 — already documented)
    - SNMP default community (F2 — already documented)
    - route daemon protocol discriminator (MTIK-ROUTE-F01 — this session)
    - libuhttp.so auth header parser (MTIK-HTTP-F02 — this session)
"""

BINARY_PATH = "/nova/bin/moduler"
VERSION = "7.24.2"

FINDINGS = [
    {
        "id": "MTIK-MOD-F01",
        "severity": "LOW",
        "title": "execl path built from USB device descriptors — physical access only",
        "description": (
            "execl() invoked with a path constructed from driver names and USB descriptor "
            "strings. Path always rooted at '/dev/'. No remote input channel. Physical USB "
            "device with crafted descriptor string required."
        ),
        "status": "LOW — physical attack surface only",
    },
    {
        "id": "MTIK-MOD-F02",
        "severity": "INFO",
        "title": "strcpy of 7-byte constant '64 bit' into 700-byte buffer — safe",
        "description": "strcpy of hardcoded literal into oversized buffer. Compiler artifact.",
        "status": "CLOSED — not exploitable",
    },
    {
        "id": "MTIK-MOD-F03",
        "severity": "INFO",
        "title": "sscanf('%x:%x') on USB descriptor content — unbounded hex read",
        "description": (
            "sscanf format '%x:%x' without field width limit on USB descriptor input. "
            "fgets limits input to 255 bytes but sscanf destination buffer sizes "
            "not confirmed. Physical USB device required."
        ),
        "status": "CANDIDATE — physical access, destination buffer size needed",
    },
    {
        "id": "MTIK-MOD-F04",
        "severity": "INFO",
        "title": "No network-reachable attack surface identified in moduler",
        "description": (
            "All input sources are /proc filesystem or USB hardware descriptors. "
            "Nova IPC messages to moduler are daemon-to-daemon (kernel socket). "
            "moduler is not a remote exploitation target."
        ),
        "status": "CLOSED for remote — out of scope for VDT on 36.64.234.59",
    },
]


def describe():
    print(f"RouterOS {VERSION} /nova/bin/moduler — RE findings summary")
    for f in FINDINGS:
        print(f"  [{f['severity']:6s}] {f['id']}: {f['title']}")
        print(f"           Status: {f['status']}")


if __name__ == "__main__":
    describe()
